import React from "react";
export default function ApiDocs() {
  return (
    <div className="min-h-screen bg-black text-white">

      {/* HEADER */}

      <section className="py-16 border-b border-gray-800">
        <div className="container mx-auto px-4 text-center">

          <h1 className="text-4xl font-bold mb-4">
            VeritasAI API Documentation
          </h1>

          <p className="text-gray-400 max-w-2xl mx-auto">
            Integrate VeritasAI detection capabilities directly into your
            applications using our REST APIs for misinformation detection,
            AI image analysis, and deepfake detection.
          </p>

        </div>
      </section>


      {/* API SECTION */}

      <section className="py-16">
        <div className="container mx-auto px-4 max-w-5xl">


          {/* AUTH SECTION */}

          <div className="bg-neutral-900 border border-gray-800 rounded-xl p-8 mb-10">

            <h2 className="text-2xl font-bold mb-4">
              Authentication
            </h2>

            <p className="text-gray-400 mb-4">
              All API requests require an API key. Include your API key in
              the Authorization header.
            </p>

            <div className="bg-black p-4 rounded-lg text-green-400 font-mono text-sm">
              Authorization: Bearer YOUR_API_KEY
            </div>

          </div>


          {/* FACT CHECK API */}

          <div className="bg-neutral-900 border border-gray-800 rounded-xl p-8 mb-10">

            <h2 className="text-2xl font-bold mb-4">
              Fact Check API
            </h2>

            <p className="text-gray-400 mb-4">
              Analyze text content or article URLs for misinformation.
            </p>

            <div className="bg-black p-4 rounded-lg text-sm font-mono overflow-x-auto">
{`POST https://api.veritasai.com/v1/fact-check

{
  "content": "Article text or URL",
  "language": "en"
}`}
            </div>

          </div>


          {/* AI IMAGE API */}

          <div className="bg-neutral-900 border border-gray-800 rounded-xl p-8 mb-10">

            <h2 className="text-2xl font-bold mb-4">
              AI Image Detection API
            </h2>

            <p className="text-gray-400 mb-4">
              Upload an image to detect if it was generated by AI.
            </p>

            <div className="bg-black p-4 rounded-lg text-sm font-mono overflow-x-auto">
{`POST https://api.veritasai.com/v1/image-detection

{
  "image": "base64_encoded_image"
}`}
            </div>

          </div>


          {/* DEEPFAKE API */}

          <div className="bg-neutral-900 border border-gray-800 rounded-xl p-8">

            <h2 className="text-2xl font-bold mb-4">
              Deepfake Detection API
            </h2>

            <p className="text-gray-400 mb-4">
              Submit a video file for deepfake analysis.
            </p>

            <div className="bg-black p-4 rounded-lg text-sm font-mono overflow-x-auto">
{`POST https://api.veritasai.com/v1/deepfake-analysis

{
  "video": "base64_encoded_video"
}`}
            </div>

          </div>

        </div>
      </section>


      {/* FOOTER */}

      <footer className="border-t border-gray-800 py-6 text-center text-gray-500">
        © 2024 VeritasAI API Platform
      </footer>

    </div>
  );
}